[package]
name = "rnnoise4j"
version = "2.0.3"
edition = "2021"

[dependencies]
jni = "0.21.1"
nnnoiseless = "0.5.1"

[lib]
crate_type = ["cdylib"]

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
panic = "abort"
strip = "symbols"
debug = false
